var constantArray = [
	"API_REQUEST_START",
	"API_REQUEST_SUCCESS",
	"API_REQUEST_FAIL",
	"API_REQUEST_ERROR",

	"ADD_ERROR",
	"CLEAR_ERROR",
	"ADD_MESSAGE",
	"CLEAR_MESSAGE",
	
	"LOGIN_COMPANY_CACHE_SUCCESS",
	"LOGIN_COMPANY_CACHE_FAIL",
	"LOGIN_COMPANY_BACKEND_SUCCESS",
	"LOGIN_COMPANY_BACKEND_FAIL",
	"LOGOUT_COMPANY",
	"LOGOUT_COMPANY_SUCCESS",
	"LOAD_COMPANY",
	"LOAD_COMPANY_BACKEND_SUCCESS",
	"LOAD_COMPANY_BACKEND_FAIL",

	// "CREATE_EMPLOYEE_BACKEND_SUCCESS",
	"CREATE_EMPLOYEE_BACKEND_FAIL",

	"LOGIN_EMPLOYEE_BACKEND_SUCCESS",
	"LOAD_EMPLOYEE_BACKEND_SUCCESS",
	"EMPLOYEE_LOGOUT",

	"USER_LOGIN",
	"USER_LOGIN_SUCCESS",
	"USER_LOGIN_FAIL",

	"LOGOUT_USER",
	"LOGOUT_USER_SUCCESS",

	"SHOW_CREATE_EMPLOYEE_PANEL",
	"CREATE_EMPLOYEE_PANEL",

	"ADD_CURRENT_WORKING_ITEM",

	// Time Punch
	"TIME_PUNCH_ON_DUTY",
	"TIME_PUNCH_BREAK",
	"TIME_PUNCH_OFF_DUTY",

	// Async Storage Key
	"CURRENT_LOGIN_COMPANY_ID",
	"CURRENT_LOGIN_COMPANY_DATA",
	"EMPLOYEE_DATA",
];

var constantObject = {};
constantArray.forEach(function(constant){
	constantObject[constant] = constant;
});

module.exports = constantObject;