"use strict";

var Constants = {
	LOAD_COMPANY: "LOAD_COMPANY",
	LOAD_COMPANY_SUCCESS: "LOAD_COMPANY_SUCCESS",
	LOAD_COMPANY_FAIL: "LOAD_COMPANY_FAIL",

	LOGIN_EMPLOYEE: "LOGIN_EMPLOYEE",
	LOGOUT_EMPLOYEE: "LOGOUT_EMPLOYEE",

	ADD_PUNCH_RECORD: "ADD_PUNCH_RECORD",
	ADD_PUNCH_RECORD_SUCCESS: "ADD_PUNCH_RECORD_SUCCESS",
	ADD_PUNCH_RECORD_FAIL: "ADD_PUNCH_RECORD_FAIL"
};

module.exports = Constants;