"use strict";

var Constants = {
	LOAD_COMPANY: "LOAD_COMPANY",
	LOAD_COMPANY_SUCCESS: "LOAD_COMPANY_SUCCESS",
	LOAD_COMPANY_FAIL: "LOAD_COMPANY_FAIL",

	LOGIN_EMPLOYEE: "LOGIN_EMPLOYEE",
	LOGOUT_EMPLOYEE: "LOGOUT_EMPLOYEE",

	ADD_PUNCH_RECORD: "ADD_PUNCH_RECORD",
	ADD_PUNCH_RECORD_SUCCESS: "ADD_PUNCH_RECORD_SUCCESS",
	// ADD_PUNCH_RECORD_FAIL: "ADD_PUNCH_RECORD_FAIL",

	CREATE_EMPTY_WORKING_ITEM_LIST: "CREATE_EMPTY_WORKING_ITEM_LIST",
	CHANGE_WORKING_ITEM_SCORE: "CHANGE_WORKING_ITEM_SCORE",
	ADD_WORKING_ITEM_LIST: "ADD_WORKING_ITEM_LIST",
	ADD_WORKING_ITEM_LIST_SUCCESS: "ADD_WORKING_ITEM_LIST_SUCCESS",
};

module.exports = Constants;